---

- name: This playbook will demonstrate with items loop 
  hosts: all
  become: yes

  vars:
    packages:
      - tree
      - vim 
      - wget 


  tasks:
    - name: Install a bunch of software tools
      apt: name="{{item}}" state=present update_cache=yes 
      with_items: "{{packages}}"

