---

- name: Install nginx web server in Ubuntu server 
  apt: name=nginx state=present update_cache=yes
  when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" )

- name: Install epel release package
  yum: name=epel-release state=present
  when: ( ansible_os_family == "RedHat" and ansible_distribution == "CentOS" )

- name: Install nginx web server in CentOS sever
  yum: name=nginx state=present
  when: ( ansible_os_family == "RedHat" and ansible_distribution == "CentOS" )
